### ISSUE TITLE
using es6 modules!!

### ISSUE THREAD

**Issue by Malouda** [jonjaques/react-loaders#19]
Please update the docs!!!
in the docs i think it should be 
`import {Loader} from 'react-loaders';`
instead of 
`import Loader from 'react-loaders';`

**Comment by jonjaques** [comment]
Hi there,

It is buried on [#54](https://github.com/jonjaques/react-loaders/blob/master/src/index.js#L54), but I believe you should be able to do both.

Is the default export not working for you?

**Comment by jonjaques** [comment]
I believe both `import {Loader} from 'react-loaders'` and `import Loader from 'react-loaders'` should work. If somebody wants to argue why that's a bad idea (prolly), feel free to submit a PR and we will semver major. Closing for now 😄

**Comment by casoetan** [comment]
@jonjaques <code>import Loader from 'react-loaders'</code> does not work. I've spent the better part of the last 3 hours trying to get this running. This <code>import {Loader} from 'react-loaders'</code> actually works.

**Comment by jonjaques** [comment]
Ok, you're right - much apologies for any inconvenience caused. Basically the issue was we were using `commonjs` target in webpack, which creates `exports.default` however it does not do `exports._esModule = true`. This fouls up Babel's `requireInterop` function because it is expecting the `_esModule` flag to be there. Commonjs2 resolves the issue. Fixed in `2.6.1`!
